services:
  - type: web
    name: secure-study-hub-backend
    env: node
    plan: starter
    rootDir: secure-study-hub-backend
    buildCommand: npm install --include=dev && npm run prisma:generate && npm run build
    startCommand: npm run prisma:deploy && npm start
    envVars:
      - key: PORT
        value: 4000
      - key: NODE_ENV
        value: production