services:
  - type: web
    name: secure-study-hub-backend
    env: node
    plan: starter
    rootDir: secure-study-hub-backend
    buildCommand: npm install --include=dev && npm run prisma:generate && npm run build
    preDeployCommand: npm run prisma:deploy
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production